import {
  Calendar, Briefcase, ClipboardList, FileText, TrendingUp,
  Code2, FileCode, Tag,
  BookOpen, BookMarked, GraduationCap,
  PenTool, Megaphone, Feather,
  User, ScrollText, Scale,
} from 'lucide-react';

export interface Template {
  id: string;
  name: string;
  icon: any;
  description: string;
  category: string;
  content: any;
}

export const templates: Template[] = [
  {
    id: 'meeting-notes', name: 'Meeting Notes', icon: Calendar,
    description: 'Structured meeting notes with agenda, discussion points, and action items',
    category: 'Business',
    content: { type: 'doc', content: [
      { type: 'heading', attrs: { level: 1 }, content: [{ type: 'text', text: 'Meeting Notes' }] },
      { type: 'paragraph', content: [
        { type: 'text', marks: [{ type: 'bold' }], text: 'Date: ' },
        { type: 'text', text: '[Insert Date]' },
      ]},
      { type: 'paragraph', content: [
        { type: 'text', marks: [{ type: 'bold' }], text: 'Time: ' },
        { type: 'text', text: '[Start Time] - [End Time]' },
      ]},
      { type: 'paragraph', content: [
        { type: 'text', marks: [{ type: 'bold' }], text: 'Location: ' },
        { type: 'text', text: '[Room / Video Link]' },
      ]},
      { type: 'paragraph', content: [
        { type: 'text', marks: [{ type: 'bold' }], text: 'Attendees: ' },
        { type: 'text', text: '[Name 1, Name 2, Name 3]' },
      ]},
      { type: 'horizontalRule' },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Agenda' }] },
      { type: 'orderedList', content: [
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Review previous action items' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Project status updates' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Discussion on new initiatives' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Any other business' }] }] },
      ]},
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Discussion Points' }] },
      { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: '1. Project Alpha Update' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Summary of discussion on Project Alpha progress and blockers]' }] },
      { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: '2. Q3 Planning' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Discussion on Q3 goals, resource allocation, and timelines]' }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Decisions Made' }] },
      { type: 'bulletList', content: [
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Decision 1: [Description]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Decision 2: [Description]' }] }] },
      ]},
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Action Items' }] },
      { type: 'bulletList', content: [
        { type: 'listItem', content: [{ type: 'paragraph', content: [
          { type: 'text', text: '[Task description] — ' },
          { type: 'text', marks: [{ type: 'bold' }], text: 'Owner: ' },
          { type: 'text', text: '[Name], ' },
          { type: 'text', marks: [{ type: 'bold' }], text: 'Due: ' },
          { type: 'text', text: '[Date]' },
        ]}]},
        { type: 'listItem', content: [{ type: 'paragraph', content: [
          { type: 'text', text: '[Task description] — ' },
          { type: 'text', marks: [{ type: 'bold' }], text: 'Owner: ' },
          { type: 'text', text: '[Name], ' },
          { type: 'text', marks: [{ type: 'bold' }], text: 'Due: ' },
          { type: 'text', text: '[Date]' },
        ]}]},
      ]},
      { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'italic' }], text: 'Next meeting: [Date & Time]' }] },
    ]},
  },
  {
    id: 'project-proposal', name: 'Project Proposal', icon: Briefcase,
    description: 'Professional project proposal with objectives, scope, timeline, and budget',
    category: 'Business',
    content: { type: 'doc', content: [
      { type: 'heading', attrs: { level: 1 }, content: [{ type: 'text', text: 'Project Proposal' }] },
      { type: 'paragraph', content: [
        { type: 'text', marks: [{ type: 'italic' }], text: 'Prepared by: ' },
        { type: 'text', text: '[Your Name]' },
      ]},
      { type: 'paragraph', content: [
        { type: 'text', marks: [{ type: 'italic' }], text: 'Date: ' },
        { type: 'text', text: '[Date]' },
      ]},
      { type: 'horizontalRule' },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Executive Summary' }] },
      { type: 'paragraph', content: [{ type: 'text', text: 'This proposal outlines a plan to [brief description of project]. The project aims to [primary goal] and is expected to deliver [key outcomes]. The total estimated budget is $[Amount] with a timeline of [Duration].' }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Objectives' }] },
      { type: 'orderedList', content: [
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Objective 1: [Specific, measurable goal]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Objective 2: [Specific, measurable goal]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Objective 3: [Specific, measurable goal]' }] }] },
      ]},
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Scope' }] },
      { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'In Scope:' }] },
      { type: 'bulletList', content: [
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Deliverable or activity included]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Deliverable or activity included]' }] }] },
      ]},
      { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Out of Scope:' }] },
      { type: 'bulletList', content: [
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Deliverable or activity excluded]' }] }] },
      ]},
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Timeline' }] },
      { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Phase 1: Planning' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Start Date] — [End Date]' }] },
      { type: 'bulletList', content: [
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Requirements gathering' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Stakeholder alignment' }] }] },
      ]},
      { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Phase 2: Execution' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Start Date] — [End Date]' }] },
      { type: 'bulletList', content: [
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Development / implementation' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Testing and QA' }] }] },
      ]},
      { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Phase 3: Launch' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Start Date] — [End Date]' }] },
      { type: 'bulletList', content: [
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Deployment' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Post-launch monitoring' }] }] },
      ]},
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Budget' }] },
      { type: 'bulletList', content: [
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Personnel: $[Amount]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Software / Tools: $[Amount]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Infrastructure: $[Amount]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Contingency (10%): $[Amount]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Total: $[Amount]' }] }] },
      ]},
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Success Metrics' }] },
      { type: 'bulletList', content: [
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Metric 1] — target value' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Metric 2] — target value' }] }] },
      ]},
    ]},
  },
  {
    id: 'weekly-report', name: 'Weekly Report', icon: ClipboardList,
    description: 'Track weekly accomplishments, challenges, and goals',
    category: 'Business',
    content: { type: 'doc', content: [
      { type: 'heading', attrs: { level: 1 }, content: [{ type: 'text', text: 'Weekly Report' }] },
      { type: 'paragraph', content: [
        { type: 'text', marks: [{ type: 'bold' }], text: 'Week of: ' },
        { type: 'text', text: '[Date]' },
      ]},
      { type: 'paragraph', content: [
        { type: 'text', marks: [{ type: 'bold' }], text: 'Author: ' },
        { type: 'text', text: '[Your Name]' },
      ]},
      { type: 'horizontalRule' },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Accomplishments' }] },
      { type: 'bulletList', content: [
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Completed [Task/Project] — [brief outcome]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Resolved [Issue/Blocker] — [resolution]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Attended [Meeting/Event] — [key takeaway]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Delivered [Deliverable] ahead of schedule' }] }] },
      ]},
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Challenges & Blockers' }] },
      { type: 'bulletList', content: [
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Challenge] — impact: [description] — mitigation: [plan]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Blocker] — needs input from [Person/Team]' }] }] },
      ]},
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Key Metrics' }] },
      { type: 'bulletList', content: [
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Tasks completed: [X] / [Y]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Hours logged: [X]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Code commits: [X]' }] }] },
      ]},
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Next Week Plans' }] },
      { type: 'orderedList', content: [
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Priority 1 task]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Priority 2 task]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Priority 3 task]' }] }] },
      ]},
    ]},
  },
  {
    id: 'business-letter', name: 'Business Letter', icon: FileText,
    description: 'Formal business letter with professional formatting',
    category: 'Business',
    content: { type: 'doc', content: [
      { type: 'paragraph', content: [{ type: 'text', text: '[Your Name]' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Your Title/Position]' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Company Name]' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Street Address]' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[City, State ZIP Code]' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Email Address] | [Phone Number]' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Date]' }] },
      { type: 'horizontalRule' },
      { type: 'paragraph', content: [
        { type: 'text', text: '[Recipient Name]' },
      ]},
      { type: 'paragraph', content: [{ type: 'text', text: '[Recipient Title]' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Company Name]' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Address]' }] },
      { type: 'horizontalRule' },
      { type: 'paragraph', content: [
        { type: 'text', marks: [{ type: 'bold' }], text: 'Re: [Subject Line]' },
      ]},
      { type: 'paragraph', content: [{ type: 'text', text: 'Dear [Mr./Ms. Last Name],' }] },
      { type: 'paragraph' },
      { type: 'paragraph', content: [{ type: 'text', text: '[Opening paragraph — state the purpose of your letter. Briefly introduce yourself if necessary and explain why you are writing.]' }] },
      { type: 'paragraph' },
      { type: 'paragraph', content: [{ type: 'text', text: '[Body paragraph 1 — provide details, context, and supporting information. Be clear and concise about your main points.]' }] },
      { type: 'paragraph' },
      { type: 'paragraph', content: [{ type: 'text', text: '[Body paragraph 2 — include any additional information, requests, or next steps. Use specific examples where appropriate.]' }] },
      { type: 'paragraph' },
      { type: 'paragraph', content: [{ type: 'text', text: '[Closing paragraph — summarize, state desired action, and express gratitude.]' }] },
      { type: 'paragraph' },
      { type: 'paragraph', content: [{ type: 'text', text: 'Sincerely,' }] },
      { type: 'paragraph' },
      { type: 'paragraph', content: [{ type: 'text', text: '[Your Name]' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Your Title]' }] },
      { type: 'paragraph' },
      { type: 'paragraph', content: [
        { type: 'text', marks: [{ type: 'italic' }], text: 'Enclosure: [List of enclosures, if any]' },
      ]},
    ]},
  },
  {
    id: 'marketing-plan', name: 'Marketing Plan', icon: TrendingUp,
    description: 'Strategic marketing plan with goals, channels, and KPIs',
    category: 'Business',
    content: { type: 'doc', content: [
      { type: 'heading', attrs: { level: 1 }, content: [{ type: 'text', text: 'Marketing Plan' }] },
      { type: 'paragraph', content: [
        { type: 'text', marks: [{ type: 'italic' }], text: 'Prepared for: ' },
        { type: 'text', text: '[Company/Product Name]' },
      ]},
      { type: 'paragraph', content: [
        { type: 'text', marks: [{ type: 'italic' }], text: 'Period: ' },
        { type: 'text', text: '[Q1 2025 — Q4 2025]' },
      ]},
      { type: 'horizontalRule' },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Executive Summary' }] },
      { type: 'paragraph', content: [{ type: 'text', text: 'This marketing plan outlines the strategy to [primary marketing goal]. The target audience is [audience description], and we will focus on [key channels]. The projected budget is $[Amount] with an expected ROI of [X]%.' }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Target Audience' }] },
      { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Demographics:' }] },
      { type: 'bulletList', content: [
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Age range: [25-45]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Location: [Region/Global]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Income level: [$X-$Y]' }] }] },
      ]},
      { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Psychographics:' }] },
      { type: 'bulletList', content: [
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Interests: [key interests]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Pain points: [challenges they face]' }] }] },
      ]},
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Marketing Channels' }] },
      { type: 'bulletList', content: [
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Email marketing: [strategy description]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Social media: [platforms and approach]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Content marketing: [blog, video, podcast]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Paid advertising: [Google Ads, social ads]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Partnerships: [affiliates, influencers]' }] }] },
      ]},
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Goals & KPIs' }] },
      { type: 'bulletList', content: [
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Increase brand awareness: [X]% growth in impressions' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Lead generation: [X] new leads per quarter' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Conversion rate: [X]%' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Customer acquisition cost: $[X]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'ROI target: [X]%' }] }] },
      ]},
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Budget Allocation' }] },
      { type: 'bulletList', content: [
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Paid ads: $[X] ([X]%)' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Content creation: $[X] ([X]%)' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Tools & software: $[X] ([X]%)' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Events: $[X] ([X]%)' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Total: $[X]' }] }] },
      ]},
    ]},
  },
  {
    id: 'technical-spec', name: 'Technical Specification', icon: Code2,
    description: 'Detailed technical specification with architecture and API design',
    category: 'Technical',
    content: { type: 'doc', content: [
      { type: 'heading', attrs: { level: 1 }, content: [{ type: 'text', text: 'Technical Specification' }] },
      { type: 'paragraph', content: [
        { type: 'text', marks: [{ type: 'italic' }], text: 'Project: ' },
        { type: 'text', text: '[Project Name]' },
      ]},
      { type: 'paragraph', content: [
        { type: 'text', marks: [{ type: 'italic' }], text: 'Version: ' },
        { type: 'text', text: '1.0' },
      ]},
      { type: 'horizontalRule' },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Overview' }] },
      { type: 'paragraph', content: [{ type: 'text', text: 'This document describes the technical architecture and implementation details for [Project Name]. The system is built using [tech stack] and follows [architecture pattern].' }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'System Architecture' }] },
      { type: 'paragraph', content: [{ type: 'text', text: 'The system follows a [microservices/monolithic/serverless] architecture with the following components:' }] },
      { type: 'bulletList', content: [
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Frontend: [Framework] — handles UI and client-side logic' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Backend API: [Framework] — RESTful API service' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Database: [Database] — primary data store' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Cache: [Redis/Memcached] — caching layer' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Message Queue: [RabbitMQ/SQS] — async processing' }] }] },
      ]},
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Tech Stack' }] },
      { type: 'bulletList', content: [
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Runtime: Node.js 20 LTS' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Language: TypeScript 5.x' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Framework: Next.js 14 (App Router)' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'ORM: Prisma' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Database: PostgreSQL 16' }] }] },
      ]},
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'API Design' }] },
      { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Authentication' }] },
      { type: 'codeBlock', content: [{ type: 'text', text: 'POST /api/auth/login\n  Body: { email, password }\n  Response: { token, user }\n\nPOST /api/auth/register\n  Body: { name, email, password }\n  Response: { token, user }' }] },
      { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Resources' }] },
      { type: 'codeBlock', content: [{ type: 'text', text: 'GET    /api/v1/resources      — List all resources\nPOST   /api/v1/resources      — Create a resource\nGET    /api/v1/resources/:id   — Get resource by ID\nPATCH  /api/v1/resources/:id   — Update resource\nDELETE /api/v1/resources/:id   — Delete resource' }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Data Model' }] },
      { type: 'codeBlock', content: [{ type: 'text', text: 'model Resource {\n  id        String   @id @default(cuid())\n  title     String\n  content   Json?\n  status    Status   @default(DRAFT)\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n  ownerId   String\n  owner     User     @relation(fields: [ownerId], references: [id])\n}' }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Security Considerations' }] },
      { type: 'bulletList', content: [
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'All endpoints require JWT authentication except public routes' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Rate limiting: 100 requests/minute per user' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Input validation using Zod schemas' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'CORS configured for allowed origins only' }] }] },
      ]},
    ]},
  },
  {
    id: 'api-documentation', name: 'API Documentation', icon: FileCode,
    description: 'Comprehensive API docs with endpoints, parameters, and examples',
    category: 'Technical',
    content: { type: 'doc', content: [
      { type: 'heading', attrs: { level: 1 }, content: [{ type: 'text', text: 'API Documentation' }] },
      { type: 'paragraph', content: [
        { type: 'text', marks: [{ type: 'italic' }], text: 'Base URL: ' },
        { type: 'text', text: 'https://api.example.com/v1' },
      ]},
      { type: 'paragraph', content: [
        { type: 'text', marks: [{ type: 'italic' }], text: 'Version: ' },
        { type: 'text', text: '1.0.0' },
      ]},
      { type: 'horizontalRule' },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Authentication' }] },
      { type: 'paragraph', content: [{ type: 'text', text: 'All API requests require an API key passed in the Authorization header:' }] },
      { type: 'codeBlock', content: [{ type: 'text', text: 'Authorization: Bearer <your-api-key>' }] },
      { type: 'paragraph', content: [{ type: 'text', text: 'To obtain an API key, register at [dashboard URL] and generate a key in your settings.' }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Users' }] },
      { type: 'heading', attrs: { level: 3 }, content: [{ type: 'text', text: 'Get User Profile' }] },
      { type: 'codeBlock', content: [{ type: 'text', text: 'GET /users/:id\n\nResponse 200:\n{\n  "id": "usr_123",\n  "name": "John Doe",\n  "email": "john@example.com",\n  "avatar": "https://...",\n  "createdAt": "2024-01-15T10:00:00Z"\n}' }] },
      { type: 'heading', attrs: { level: 3 }, content: [{ type: 'text', text: 'Update User Profile' }] },
      { type: 'codeBlock', content: [{ type: 'text', text: 'PATCH /users/:id\nContent-Type: application/json\n\nBody:\n{\n  "name": "Jane Doe",\n  "avatar": "https://..."\n}\n\nResponse 200:\n{\n  "id": "usr_123",\n  "name": "Jane Doe",\n  "email": "john@example.com"\n}' }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Documents' }] },
      { type: 'heading', attrs: { level: 3 }, content: [{ type: 'text', text: 'List Documents' }] },
      { type: 'codeBlock', content: [{ type: 'text', text: 'GET /documents?page=1&limit=20&search=keyword\n\nQuery Parameters:\n  page   (number)  — Page number (default: 1)\n  limit  (number)  — Items per page (default: 20, max: 100)\n  search (string)  — Search by title\n\nResponse 200:\n{\n  "documents": [...],\n  "total": 42,\n  "totalPages": 3,\n  "page": 1\n}' }] },
      { type: 'heading', attrs: { level: 3 }, content: [{ type: 'text', text: 'Create Document' }] },
      { type: 'codeBlock', content: [{ type: 'text', text: 'POST /documents\nContent-Type: application/json\n\nBody:\n{\n  "title": "My Document",\n  "content": { "type": "doc", "content": [] }\n}\n\nResponse 201:\n{\n  "id": "doc_456",\n  "title": "My Document",\n  "content": { ... },\n  "createdAt": "2024-06-01T12:00:00Z"\n}' }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Error Codes' }] },
      { type: 'bulletList', content: [
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '400 — Bad Request: Invalid input parameters' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '401 — Unauthorized: Missing or invalid API key' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '403 — Forbidden: Insufficient permissions' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '404 — Not Found: Resource does not exist' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '429 — Rate Limit Exceeded: Too many requests' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '500 — Internal Server Error: Something went wrong' }] }] },
      ]},
    ]},
  },
  {
    id: 'release-notes', name: 'Release Notes', icon: Tag,
    description: 'Document version releases with features, fixes, and migration guide',
    category: 'Technical',
    content: { type: 'doc', content: [
      { type: 'heading', attrs: { level: 1 }, content: [{ type: 'text', text: 'Release Notes' }] },
      { type: 'paragraph', content: [
        { type: 'text', marks: [{ type: 'bold' }], text: 'Version: ' },
        { type: 'text', text: 'v2.5.0' },
      ]},
      { type: 'paragraph', content: [
        { type: 'text', marks: [{ type: 'bold' }], text: 'Release Date: ' },
        { type: 'text', text: '[Month DD, YYYY]' },
      ]},
      { type: 'horizontalRule' },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'What\'s New' }] },
      { type: 'bulletList', content: [
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Feature 1] — [brief description of the new feature and its benefit]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Feature 2] — [brief description of the new feature and its benefit]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Feature 3] — [brief description of the new feature and its benefit]' }] }] },
      ]},
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Improvements' }] },
      { type: 'bulletList', content: [
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Improved [area] — [description of improvement, e.g., "40% faster load times"]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Redesigned [component] — [description of UX improvement]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Updated [dependency] to v[X] for security patches' }] }] },
      ]},
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Bug Fixes' }] },
      { type: 'bulletList', content: [
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Fixed [issue] where [description of bug and its impact]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Resolved [error] occurring when [scenario]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Addressed [edge case] in [component/feature]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Fixed [security vulnerability] — Credit: [reporter]' }] }] },
      ]},
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Breaking Changes' }] },
      { type: 'bulletList', content: [
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: '[Change 1]: ' }, { type: 'text', text: '[Description of breaking change and migration steps]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: '[Change 2]: ' }, { type: 'text', text: '[Description of breaking change and migration steps]' }] }] },
      ]},
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Upgrade Guide' }] },
      { type: 'orderedList', content: [
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Backup your current data and configuration' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Review breaking changes and update your code accordingly' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Run migration scripts: [command]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Deploy to staging environment and verify' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Deploy to production' }] }] },
      ]},
    ]},
  },
  {
    id: 'research-paper', name: 'Research Paper', icon: BookOpen,
    description: 'Academic research paper with abstract, methodology, and references',
    category: 'Academic',
    content: { type: 'doc', content: [
      { type: 'heading', attrs: { level: 1 }, content: [{ type: 'text', text: '[Research Paper Title]' }] },
      { type: 'paragraph', content: [
        { type: 'text', marks: [{ type: 'italic' }], text: '[Author Name(s)]' },
      ]},
      { type: 'paragraph', content: [
        { type: 'text', marks: [{ type: 'italic' }], text: '[Department, University]' },
      ]},
      { type: 'paragraph', content: [
        { type: 'text', marks: [{ type: 'italic' }], text: '[Date]' },
      ]},
      { type: 'horizontalRule' },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Abstract' }] },
      { type: 'paragraph', content: [{ type: 'text', text: 'This paper investigates [research question/topic]. Using [methodology], we analyze [data/subject] to understand [phenomenon]. Our findings indicate that [key result]. These findings have implications for [field/application] and suggest [future direction].' }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '1. Introduction' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Background context and motivation for the research. Describe the problem or gap in existing knowledge that this paper addresses.]' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Research question and hypotheses. Outline the main contributions of this work.]' }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '2. Literature Review' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Summary of relevant prior work. Discuss key theories, findings, and approaches from previous research.]' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Identify the gap in the literature that your work addresses.]' }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '3. Methodology' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Describe the research design, data collection methods, and analytical approach.]' }] },
      { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: '3.1 Data Collection' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Details on how data was gathered, sample size, instruments used.]' }] },
      { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: '3.2 Analysis' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Statistical or qualitative methods used to analyze the data.]' }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '4. Results' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Present the findings of the study. Use tables and figures as appropriate.]' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Key finding 1 with supporting data.]' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Key finding 2 with supporting data.]' }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '5. Discussion' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Interpretation of results. How do the findings relate to the research question and existing literature?]' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Limitations of the study and directions for future research.]' }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '6. Conclusion' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Summary of the main findings and their significance. Final thoughts and practical implications.]' }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'References' }] },
      { type: 'orderedList', content: [
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Author], [Title], [Journal], [Year]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Author], [Title], [Journal], [Year]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Author], [Title], [Publisher], [Year]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Author], [Title], [Conference], [Year]' }] }] },
      ]},
    ]},
  },
  {
    id: 'study-notes', name: 'Study Notes', icon: BookMarked,
    description: 'Organized study notes with key concepts, definitions, and summaries',
    category: 'Academic',
    content: { type: 'doc', content: [
      { type: 'heading', attrs: { level: 1 }, content: [{ type: 'text', text: 'Study Notes' }] },
      { type: 'paragraph', content: [
        { type: 'text', marks: [{ type: 'bold' }], text: 'Subject: ' },
        { type: 'text', text: '[Subject Name]' },
      ]},
      { type: 'paragraph', content: [
        { type: 'text', marks: [{ type: 'bold' }], text: 'Topic: ' },
        { type: 'text', text: '[Topic Name]' },
      ]},
      { type: 'paragraph', content: [
        { type: 'text', marks: [{ type: 'bold' }], text: 'Date: ' },
        { type: 'text', text: '[Date]' },
      ]},
      { type: 'horizontalRule' },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Key Concepts' }] },
      { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Concept 1: [Name]' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Definition and explanation of concept 1. Include key details, formulas, or principles.]' }] },
      { type: 'blockquote', content: [{ type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'italic' }], text: 'Key insight: [Important takeaway or mnemonic]' }] }] },
      { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Concept 2: [Name]' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Definition and explanation of concept 2. Include examples where applicable.]' }] },
      { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Concept 3: [Name]' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Definition and explanation of concept 3.]' }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Important Definitions' }] },
      { type: 'bulletList', content: [
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Term 1: ' }, { type: 'text', text: 'Definition' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Term 2: ' }, { type: 'text', text: 'Definition' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Term 3: ' }, { type: 'text', text: 'Definition' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Term 4: ' }, { type: 'text', text: 'Definition' }] }] },
      ]},
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Examples' }] },
      { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Example 1:' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Step-by-step example demonstrating concept application]' }] },
      { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Example 2:' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Step-by-step example demonstrating concept application]' }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Summary' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Brief summary of the key takeaways from this topic. What you should remember.]' }] },
      { type: 'paragraph', content: [
        { type: 'text', marks: [{ type: 'bold' }], text: 'Review questions:' },
      ]},
      { type: 'bulletList', content: [
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Question 1]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Question 2]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Question 3]' }] }] },
      ]},
    ]},
  },
  {
    id: 'lesson-plan', name: 'Lesson Plan', icon: GraduationCap,
    description: 'Structured lesson plan with objectives, activities, and assessment',
    category: 'Academic',
    content: { type: 'doc', content: [
      { type: 'heading', attrs: { level: 1 }, content: [{ type: 'text', text: 'Lesson Plan' }] },
      { type: 'paragraph', content: [
        { type: 'text', marks: [{ type: 'bold' }], text: 'Subject: ' },
        { type: 'text', text: '[Subject]' },
      ]},
      { type: 'paragraph', content: [
        { type: 'text', marks: [{ type: 'bold' }], text: 'Grade Level: ' },
        { type: 'text', text: '[Grade]' },
      ]},
      { type: 'paragraph', content: [
        { type: 'text', marks: [{ type: 'bold' }], text: 'Duration: ' },
        { type: 'text', text: '[Minutes/Periods]' },
      ]},
      { type: 'horizontalRule' },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Learning Objectives' }] },
      { type: 'paragraph', content: [{ type: 'text', text: 'By the end of this lesson, students will be able to:' }] },
      { type: 'orderedList', content: [
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Objective 1 — specific, measurable outcome]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Objective 2 — specific, measurable outcome]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Objective 3 — specific, measurable outcome]' }] }] },
      ]},
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Materials Needed' }] },
      { type: 'bulletList', content: [
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Material 1]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Material 2]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Material 3]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Technology / tools]' }] }] },
      ]},
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Lesson Procedure' }] },
      { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: '1. Introduction / Hook (5 min)' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Engaging opening activity to capture student interest and activate prior knowledge]' }] },
      { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: '2. Direct Instruction (15 min)' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Present new content using lecture, demonstration, or multimedia. Key points to cover:]' }] },
      { type: 'bulletList', content: [
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Key point 1]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Key point 2]' }] }] },
      ]},
      { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: '3. Guided Practice (15 min)' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Students work through examples with teacher guidance. Activity description:]' }] },
      { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: '4. Independent Practice (10 min)' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Students work independently on an assignment or activity to demonstrate understanding]' }] },
      { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: '5. Closure (5 min)' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Review key concepts, preview next lesson, exit ticket or quick assessment]' }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Assessment' }] },
      { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Formative:' }] },
      { type: 'bulletList', content: [
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Observation, questioning, exit ticket, etc.]' }] }] },
      ]},
      { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Summative:' }] },
      { type: 'bulletList', content: [
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Quiz, project, presentation, etc.]' }] }] },
      ]},
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Homework / Extension' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Assignment or extension activity for students to complete after class]' }] },
      { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'italic' }], text: 'Notes: [Self-reflection on the lesson after teaching]' }] },
    ]},
  },
  {
    id: 'blog-post', name: 'Blog Post', icon: PenTool,
    description: 'Ready-to-write blog post structure with SEO-friendly sections',
    category: 'Creative',
    content: { type: 'doc', content: [
      { type: 'heading', attrs: { level: 1 }, content: [{ type: 'text', text: '[Blog Post Title]' }] },
      { type: 'paragraph', content: [
        { type: 'text', marks: [{ type: 'italic' }], text: 'By [Author Name] · [Date] · [X min read]' },
      ]},
      { type: 'horizontalRule' },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Introduction' }] },
      { type: 'paragraph', content: [{ type: 'text', text: 'Hook your readers with an engaging opening paragraph. Start with a surprising statistic, a compelling question, or a relatable anecdote that sets up the topic. Briefly explain what the post will cover and why readers should care.' }] },
      { type: 'blockquote', content: [{ type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'italic' }], text: '"A powerful quote or statistic that reinforces your main point."' }] }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'The Problem' }] },
      { type: 'paragraph', content: [{ type: 'text', text: 'Describe the common challenge, pain point, or question your readers are facing. Help them feel understood before presenting your solution.' }] },
      { type: 'bulletList', content: [
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Common symptom or sign of the problem]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Why existing solutions fall short]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[The cost of not solving this problem]' }] }] },
      ]},
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'The Solution' }] },
      { type: 'paragraph', content: [{ type: 'text', text: 'Present your main idea, framework, or step-by-step solution. Break this section into digestible subheadings.' }] },
      { type: 'heading', attrs: { level: 3 }, content: [{ type: 'text', text: 'Step 1: [First Step]' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Detailed explanation of the first step. Include specific actions the reader can take.]' }] },
      { type: 'heading', attrs: { level: 3 }, content: [{ type: 'text', text: 'Step 2: [Second Step]' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Detailed explanation of the second step. Share tips and best practices.]' }] },
      { type: 'heading', attrs: { level: 3 }, content: [{ type: 'text', text: 'Step 3: [Third Step]' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Detailed explanation of the third step. Include examples or case studies.]' }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Practical Tips' }] },
      { type: 'bulletList', content: [
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Tip 1 with brief explanation]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Tip 2 with brief explanation]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Tip 3 with brief explanation]' }] }] },
      ]},
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Conclusion' }] },
      { type: 'paragraph', content: [{ type: 'text', text: 'Summarize the main takeaways and reinforce the key message. End with a call to action that encourages readers to engage — leave a comment, share the post, try the technique, or sign up for more content.' }] },
      { type: 'paragraph', content: [
        { type: 'text', marks: [{ type: 'italic' }], text: 'What\'s your experience with [topic]? Share your thoughts in the comments below!' },
      ]},
    ]},
  },
  {
    id: 'press-release', name: 'Press Release', icon: Megaphone,
    description: 'Professional press release with quote and media contact info',
    category: 'Creative',
    content: { type: 'doc', content: [
      { type: 'paragraph', content: [
        { type: 'text', marks: [{ type: 'bold' }], text: 'FOR IMMEDIATE RELEASE' },
      ]},
      { type: 'paragraph', content: [
        { type: 'text', text: '[City, State] — ' },
        { type: 'text', text: '[Month DD, YYYY]' },
      ]},
      { type: 'horizontalRule' },
      { type: 'heading', attrs: { level: 1 }, content: [{ type: 'text', text: '[Compelling Headline: Company Announces Major News]' }] },
      { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'italic' }], text: '[Subheadline: A brief supporting statement that expands on the headline]' }] },
      { type: 'horizontalRule' },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Body' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[City, State] — [Company Name] today announced [major announcement]. This [product/service/initiative] [key benefit or differentiator]. The announcement was made at [event/location] by [spokesperson name].' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Additional details about the announcement. Include the problem being solved, target audience, and key features or benefits. Second paragraph should provide more context and supporting information.]' }] },
      { type: 'blockquote', content: [{ type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'italic' }], text: '"[Quote from CEO or key executive — should convey excitement and the strategic importance of the announcement.]"' }] }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Third paragraph: Additional details, statistics, or third-party validation (analyst quotes, customer testimonials, early results).]' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Availability information: pricing, launch date, where to get it, any introductory offers.]' }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'About [Company Name]' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Company boilerplate — 2-3 sentences describing the company, its mission, and its market position.]' }] },
      { type: 'horizontalRule' },
      { type: 'heading', attrs: { level: 3 }, content: [{ type: 'text', text: 'Media Contact' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Name]' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Title]' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Email]' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Phone]' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Website URL]' }] },
      { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'italic' }], text: '###' }] },
    ]},
  },
  {
    id: 'creative-story', name: 'Creative Story', icon: Feather,
    description: 'Story outline and draft template with character and plot development',
    category: 'Creative',
    content: { type: 'doc', content: [
      { type: 'heading', attrs: { level: 1 }, content: [{ type: 'text', text: '[Story Title]' }] },
      { type: 'paragraph', content: [
        { type: 'text', marks: [{ type: 'italic' }], text: 'By [Author Name]' },
      ]},
      { type: 'horizontalRule' },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Characters' }] },
      { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Protagonist: [Name]' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Brief description: age, appearance, personality, motivation, flaw]' }] },
      { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Antagonist: [Name]' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Brief description: what drives them, why they oppose the protagonist]' }] },
      { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Supporting Characters:' }] },
      { type: 'bulletList', content: [
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: '[Name]: ' }, { type: 'text', text: '[Role and relationship to protagonist]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: '[Name]: ' }, { type: 'text', text: '[Role and relationship to protagonist]' }] }] },
      ]},
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Setting' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Time period and location. Describe the world of the story — is it realistic, fantastical, futuristic? What are the rules of this world?]' }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Plot Outline' }] },
      { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Act I: Beginning' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Establish the ordinary world. Introduce the protagonist in their everyday life. The inciting incident happens — something that changes everything.]' }] },
      { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Act II: Middle' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[The protagonist faces challenges, meets allies and enemies, and grows. Rising tension leads to the midpoint crisis.]' }] },
      { type: 'bulletList', content: [
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Scene/event 1]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Scene/event 2]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Scene/event 3 — midpoint twist]' }] }] },
      ]},
      { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Act III: End' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[The climax — protagonist confronts the antagonist or central conflict. Resolution and new normal.]' }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Themes' }] },
      { type: 'bulletList', content: [
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Theme 1 — e.g., love, loss, redemption, identity]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Theme 2]' }] }] },
      ]},
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Chapter Outline' }] },
      { type: 'orderedList', content: [
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Chapter 1: ' }, { type: 'text', text: '[Title] — Brief summary]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Chapter 2: ' }, { type: 'text', text: '[Title] — Brief summary]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Chapter 3: ' }, { type: 'text', text: '[Title] — Brief summary]' }] }] },
      ]},
      { type: 'paragraph', content: [
        { type: 'text', marks: [{ type: 'italic' }], text: 'Notes: [Any additional ideas, research needed, or brainstorming notes]' },
      ]},
    ]},
  },
  {
    id: 'cover-letter', name: 'Cover Letter', icon: User,
    description: 'Professional cover letter for job applications',
    category: 'Personal',
    content: { type: 'doc', content: [
      { type: 'paragraph', content: [{ type: 'text', text: '[Your Name]' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Your Address]' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[City, State ZIP Code]' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Phone Number]' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Email Address]' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[LinkedIn Profile / Portfolio URL]' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Date]' }] },
      { type: 'horizontalRule' },
      { type: 'paragraph', content: [{ type: 'text', text: '[Hiring Manager Name]' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Company Name]' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Company Address]' }] },
      { type: 'horizontalRule' },
      { type: 'paragraph', content: [{ type: 'text', text: 'Dear [Hiring Manager Name],' }] },
      { type: 'paragraph' },
      { type: 'paragraph', content: [{ type: 'text', text: 'I am writing to express my strong interest in the [Job Title] position at [Company Name], as advertised on [where you saw the posting]. With [X] years of experience in [field/industry] and a proven track record of [key achievement], I am confident that my skills align perfectly with the requirements of this role.' }] },
      { type: 'paragraph' },
      { type: 'paragraph', content: [{ type: 'text', text: 'In my current role as [Current Job Title] at [Current Company], I have [key responsibility/achievement 1]. Additionally, I [key responsibility/achievement 2]. These experiences have equipped me with [relevant skill 1] and [relevant skill 2], which I understand are critical for success at [Company Name].' }] },
      { type: 'paragraph' },
      { type: 'paragraph', content: [{ type: 'text', text: 'I am particularly drawn to [Company Name] because [reason for interest — mention company values, mission, products, or reputation]. I admire [specific aspect of the company] and would be excited to contribute to [specific project or goal].' }] },
      { type: 'paragraph' },
      { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Key qualifications I bring:' }] },
      { type: 'bulletList', content: [
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Qualification 1 with measurable impact]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Qualification 2 with measurable impact]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Qualification 3 with measurable impact]' }] }] },
      ]},
      { type: 'paragraph' },
      { type: 'paragraph', content: [{ type: 'text', text: 'I would welcome the opportunity to discuss how my background and skills would benefit [Company Name]. Thank you for considering my application. I look forward to hearing from you.' }] },
      { type: 'paragraph' },
      { type: 'paragraph', content: [{ type: 'text', text: 'Sincerely,' }] },
      { type: 'paragraph' },
      { type: 'paragraph', content: [{ type: 'text', text: '[Your Name]' }] },
    ]},
  },
  {
    id: 'resume', name: 'Resume / CV', icon: ScrollText,
    description: 'Professional resume template with experience, education, and skills sections',
    category: 'Personal',
    content: { type: 'doc', content: [
      { type: 'heading', attrs: { level: 1 }, content: [{ type: 'text', text: '[Your Full Name]' }] },
      { type: 'paragraph', content: [
        { type: 'text', text: '[City, State] | [Phone] | [Email] | [LinkedIn] | [Portfolio]' },
      ]},
      { type: 'horizontalRule' },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Professional Summary' }] },
      { type: 'paragraph', content: [{ type: 'text', text: 'Results-driven [Job Title] with [X] years of experience in [industry/field]. Proven track record of [key achievement area], [key achievement area], and [key achievement area]. Skilled in [key skill 1], [key skill 2], and [key skill 3]. Passionate about [motivation/drive] and committed to delivering [type of results].' }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Professional Experience' }] },
      { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: '[Job Title]' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Company Name] | [City, State]' }] },
      { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'italic' }], text: '[Month YYYY] — [Month YYYY]' }] },
      { type: 'bulletList', content: [
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Accomplishment/responsibility with measurable impact — e.g., "Increased revenue by 20% through targeted outreach"]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Accomplishment/responsibility with measurable impact]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Accomplishment/responsibility with measurable impact]' }] }] },
      ]},
      { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: '[Previous Job Title]' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Previous Company] | [City, State]' }] },
      { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'italic' }], text: '[Month YYYY] — [Month YYYY]' }] },
      { type: 'bulletList', content: [
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Accomplishment/responsibility with measurable impact]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Accomplishment/responsibility with measurable impact]' }] }] },
      ]},
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Education' }] },
      { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: '[Degree Name]' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[University Name] | [City, State]' }] },
      { type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'italic' }], text: 'Graduated: [Year]' }] },
      { type: 'bulletList', content: [
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'GPA: [X.X] / 4.0' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Relevant coursework: [Course 1, Course 2, Course 3]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Honors: [Dean\'s List, Scholarship, etc.]' }] }] },
      ]},
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: 'Skills' }] },
      { type: 'bulletList', content: [
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Technical: ' }, { type: 'text', text: '[Skill 1, Skill 2, Skill 3]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Languages: ' }, { type: 'text', text: '[Language 1 (fluent), Language 2 (conversational)]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', marks: [{ type: 'bold' }], text: 'Certifications: ' }, { type: 'text', text: '[Certification 1, Certification 2]' }] }] },
      ]},
      { type: 'paragraph', content: [
        { type: 'text', marks: [{ type: 'italic' }], text: 'References available upon request.' },
      ]},
    ]},
  },
  {
    id: 'service-agreement', name: 'Service Agreement', icon: Scale,
    description: 'Standard service agreement contract with key legal clauses',
    category: 'Legal',
    content: { type: 'doc', content: [
      { type: 'heading', attrs: { level: 1 }, content: [{ type: 'text', text: 'Service Agreement' }] },
      { type: 'paragraph', content: [
        { type: 'text', marks: [{ type: 'bold' }], text: 'This Service Agreement ("Agreement") is entered into on ' },
        { type: 'text', text: '[Date]' },
      ]},
      { type: 'paragraph', content: [
        { type: 'text', marks: [{ type: 'bold' }], text: 'Between:' },
      ]},
      { type: 'paragraph', content: [{ type: 'text', text: '[Service Provider Name] ("Provider")' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Provider Address]' }] },
      { type: 'paragraph', content: [{ type: 'text', text: 'and' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Client Name] ("Client")' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '[Client Address]' }] },
      { type: 'horizontalRule' },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '1. Services' }] },
      { type: 'paragraph', content: [{ type: 'text', text: 'Provider agrees to perform the following services ("Services"):' }] },
      { type: 'orderedList', content: [
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Description of service 1]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Description of service 2]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: '[Description of service 3]' }] }] },
      ]},
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '2. Payment Terms' }] },
      { type: 'paragraph', content: [{ type: 'text', text: 'Client agrees to pay Provider the following fees:' }] },
      { type: 'bulletList', content: [
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Total fee: $[Amount]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Payment schedule: [e.g., 50% upfront, 50% upon completion]' }] }] },
        { type: 'listItem', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Payment due within [X] days of invoice date' }] }] },
      ]},
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '3. Term and Termination' }] },
      { type: 'paragraph', content: [{ type: 'text', text: 'This Agreement shall begin on [Start Date] and continue until [End Date] ("Term"), unless terminated earlier as provided below.' }] },
      { type: 'paragraph', content: [{ type: 'text', text: 'Either party may terminate this Agreement with [X] days written notice. Provider may terminate immediately if Client fails to make payment when due.' }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '4. Confidentiality' }] },
      { type: 'paragraph', content: [{ type: 'text', text: 'Both parties agree to maintain the confidentiality of all proprietary information disclosed during the term of this Agreement. Confidential information includes but is not limited to business plans, customer data, financial information, and technical specifications.' }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '5. Intellectual Property' }] },
      { type: 'paragraph', content: [{ type: 'text', text: 'Upon full payment, all intellectual property rights in the deliverables created under this Agreement shall be transferred to the Client. Provider retains the right to use general skills and knowledge gained during performance.' }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '6. Limitation of Liability' }] },
      { type: 'paragraph', content: [{ type: 'text', text: 'Provider\'s total liability under this Agreement shall not exceed the total fees paid by Client. Provider shall not be liable for any indirect, incidental, or consequential damages.' }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '7. Governing Law' }] },
      { type: 'paragraph', content: [{ type: 'text', text: 'This Agreement shall be governed by the laws of [State/Country]. Any disputes shall be resolved in the courts of [Jurisdiction].' }] },
      { type: 'horizontalRule' },
      { type: 'paragraph', content: [
        { type: 'text', marks: [{ type: 'bold' }], text: 'IN WITNESS WHEREOF', },
        { type: 'text', text: ', the parties have executed this Agreement as of the date first written above.' },
      ]},
      { type: 'paragraph' },
      { type: 'paragraph', content: [
        { type: 'text', marks: [{ type: 'bold' }], text: '[Provider Name]' },
        { type: 'text', text: '                          ' },
        { type: 'text', marks: [{ type: 'bold' }], text: '[Client Name]' },
      ]},
      { type: 'paragraph', content: [{ type: 'text', text: '_________________________               _________________________' }] },
      { type: 'paragraph', content: [{ type: 'text', text: 'Signature                                              Signature' }] },
      { type: 'paragraph', content: [{ type: 'text', text: '_________________________               _________________________' }] },
      { type: 'paragraph', content: [{ type: 'text', text: 'Date                                                       Date' }] },
    ]},
  },
];
